serialContainer
captain-yoshi/BehaviorTree.MTC pull request #12
Opened 2024-06-04 18:41 UTC by berg0401

Create MTC serial container and add it to a task container.

2024-06-04 18:41 UTC, berg0401 commented
@captain-yoshi

2024-06-07 18:10 UTC, captain-yoshi requested changes

2024-06-07 18:10 UTC, captain-yoshi commented on src/create_mtc_serial_container.cpp
> +    BT::OutputPort<MTC::ContainerBasePtr>(kPortSerialContainer, "MoveTo Serial Container"),
```suggestion
    BT::OutputPort<MTC::ContainerBasePtr>(kPortSerialContainer, "serial container"),
```

2024-06-07 18:10 UTC, captain-yoshi commented on src/move_mtc_container_to_container.cpp
> +  return NodeStatus::SUCCESS;
```suggestion
```

2024-06-07 18:10 UTC, captain-yoshi commented on src/move_mtc_container_to_container.cpp
> +      container->add(std::move(unique_container_child));
```suggestion
  MTC::ContainerBase::pointer unique_child_container{ nullptr };
  if(auto any_container_ptr = getLockedPortContent(kPortChildContainer))
  {
    if(auto* container_ptr = any_container_ptr->castPtr<MTC::ContainerBasePtr>())
    {
      auto& child_container = *container_ptr;

      unique_child_container = sharedToUnique(child_container);
      any_container_ptr.assign(nullptr);  // set blackboard value to nullptr
    }
  }

  if(auto any_container_ptr = getLockedPortContent(kPortParentContainer); unique_container_child)
  {
    if(auto* container_ptr = any_container_ptr->castPtr<MTC::ContainerBasePtr>())
    {
      auto& parent_container = *container_ptr;

      parent_container->add(std::move(unique_child_container));
```

2024-06-07 18:11 UTC, captain-yoshi commented
I would also change the name `MoveMTCContainerToContainer` to `MoveMTCContainerToParentContainer`.

2024-06-07 19:29 UTC, captain-yoshi approved these changes

2024-06-07 19:29 UTC, merged